@extends('dcc.akademik.layout')

@section('title', 'Input Nilai Siswa')
@section('breadcrumb', 'Input Nilai Siswa')

@section('content')
<div class="akademik-page-head">
  <div>
    <h1 class="akademik-page-title">{{ $distribusi->mataPelajaran?->nama_mapel }}</h1>
    <div class="akademik-page-desc">
      Kelas <strong>{{ $distribusi->rombel?->nama_rombel }}</strong> · Semester {{ $distribusi->semester }} · Guru: <strong>{{ $distribusi->guru?->nama_lengkap_gelar ?: $distribusi->guru?->nama }}</strong>
    </div>
  </div>

  <div style="display:flex; gap:10px; align-items:center; flex-wrap:wrap;">
    <form action="{{ route('akademik.nilai.sinkron_cbt', $distribusi->id) }}" method="POST" onsubmit="return confirm('Tarik dan sinkronkan hasil ujian asesmen CBT online ke buku nilai kelas ini?')" style="margin:0;">
      @csrf
      <button type="submit" class="ak-btn ak-btn-primary" style="font-weight:700;">
        <i class="bi bi-cloud-arrow-down-fill me-1"></i>
        <span>Tarik Nilai dari Asesmen CBT</span>
      </button>
    </form>
    <a href="{{ route('akademik.nilai.leger', ['rombel_id' => $distribusi->rombel_id, 'semester' => $distribusi->semester]) }}" class="ak-btn ak-btn-secondary">
      <i class="bi bi-table"></i>
      <span>Leger Kelas Ini</span>
    </a>
    <a href="{{ route('akademik.nilai.index') }}" class="ak-btn ak-btn-secondary">
      <i class="bi bi-arrow-left"></i>
      <span>Kembali</span>
    </a>
  </div>
</div>

<form action="{{ route('akademik.nilai.store', $distribusi->id) }}" method="POST">
  @csrf

  <div class="akademik-card">
    <div class="akademik-card-header" style="display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:10px;">
      <h3 class="akademik-card-title">
        <i class="bi bi-pencil-square text-primary"></i>
        <span>Lembar Penilaian Siswa ({{ $siswas->count() }} Siswa)</span>
      </h3>
      <div style="display:flex; align-items:center; gap:8px;">
        <button type="button" class="ak-btn ak-btn-secondary ak-btn-sm" onclick="autoGenerateDeskripsiCp()" style="font-weight:700; font-size:11.5px;">
          <i class="bi bi-magic text-primary me-1"></i> Auto-Generate Deskripsi dari CP
        </button>
        <span class="ak-badge ak-badge-primary">Skala 0 - 100</span>
      </div>
    </div>

    @if($distribusi->mataPelajaran?->deskripsi_cp)
      <div style="background:#f0fdf4; border-bottom:1px solid #bbf7d0; padding:12px 20px;">
        <div style="font-size:11px; font-weight:800; color:#166534; text-transform:uppercase; display:flex; align-items:center; gap:5px;">
          <i class="bi bi-bullseye text-success"></i> Capaian Pembelajaran (CP) Resmi — {{ $distribusi->mataPelajaran->fase_label }}
        </div>
        <div style="font-size:12px; color:#334155; line-height:1.45; margin-top:2px;">
          {{ $distribusi->mataPelajaran->deskripsi_cp }}
        </div>
      </div>
    @endif

    <div class="akademik-card-body" style="padding:0;">
      @if($siswas->isEmpty())
        <div style="padding:40px; text-align:center; color:#64748b;">
          Belum ada data siswa aktif di rombel ini.
        </div>
      @else
        <div class="akademik-table-wrap">
          <table class="akademik-table">
            <thead>
              <tr>
                <th style="width:40px;">No</th>
                <th style="min-width:180px;">Nama Siswa</th>
                @foreach($namaPenilaians as $penilaian)
                  <th style="min-width:100px; text-align:center;">
                    <div style="font-size:12px;">{{ $penilaian }}</div>
                    @if(str_contains(strtolower($penilaian), 'sumatif'))
                      <span class="ak-badge ak-badge-warning" style="font-size:9px; padding:1px 5px;">Sumatif</span>
                    @else
                      <span class="ak-badge ak-badge-primary" style="font-size:9px; padding:1px 5px;">Formatif</span>
                    @endif
                  </th>
                @endforeach
                <th style="min-width:240px;">Deskripsi Capaian Kompetensi</th>
              </tr>
            </thead>
            <tbody>
              @foreach($siswas as $idx => $s)
                @php
                  $scores = $existingNilai->get($s->id)?->keyBy('nama_penilaian') ?? collect();
                  $desc = $scores->first()?->deskripsi_capaian ?? '';
                @endphp
                <tr>
                  <td>{{ $idx + 1 }}</td>
                  <td>
                    <div style="font-weight:700; color:var(--ak-dark);">{{ $s->nama_lengkap }}</div>
                    <div style="font-size:11px; color:#64748b;">NISN: {{ $s->nisn ?? '-' }}</div>
                  </td>
                  @foreach($namaPenilaians as $penilaian)
                    @php
                      $currRecord = $scores->get($penilaian);
                      $currVal = $currRecord?->nilai ?? '';
                      // Smart Fallback jika data tersimpan dengan judul asesmen CBT kustom
                      if ($currVal === '') {
                        foreach ($scores as $sRecord) {
                          $sNama = strtolower($sRecord->nama_penilaian ?? '');
                          if (str_contains(strtolower($penilaian), 'sts') && (str_contains($sNama, 'sts') || str_contains($sNama, 'tengah') || str_contains($sNama, 'pts'))) {
                            $currVal = $sRecord->nilai;
                            break;
                          } elseif (str_contains(strtolower($penilaian), 'sas') && (str_contains($sNama, 'sas') || str_contains($sNama, 'akhir') || str_contains($sNama, 'pas'))) {
                            $currVal = $sRecord->nilai;
                            break;
                          }
                        }
                      }
                    @endphp
                    <td style="text-align:center;">
                      <input type="number" step="0.1" min="0" max="100"
                        name="nilai[{{ $s->id }}][{{ $penilaian }}]"
                        value="{{ $currVal }}"
                        class="ak-input"
                        style="width:75px; text-align:center; font-weight:700; padding:6px;"
                        placeholder="-">
                    </td>
                  @endforeach
                  <td>
                    <input type="text" name="deskripsi[{{ $s->id }}]"
                      value="{{ $desc }}"
                      class="ak-input"
                      style="font-size:12px; padding:6px 10px;"
                      placeholder="Contoh: Menunjukkan penguasaan sangat baik dalam...">
                  </td>
                </tr>
              @endforeach
            </tbody>
          </table>
        </div>

        <div style="padding:18px 24px; border-top:1px solid var(--ak-slate-200); display:flex; justify-content:space-between; align-items:center; background:#fafafa;">
          <div style="font-size:12px; color:#64748b;">
            <i class="bi bi-info-circle me-1"></i> Nilai Akhir &amp; Leger akan otomatis dikalkulasi saat Anda menekan tombol Simpan.
          </div>
          <button type="submit" class="ak-btn ak-btn-primary">
            <i class="bi bi-check2-circle"></i>
            <span>Simpan Nilai &amp; Kalkulasi Leger</span>
          </button>
        </div>
      @endif
    </div>
  </div>
</form>

@push('scripts')
<script>
function autoGenerateDeskripsiCp() {
  const rawCp = @json($distribusi->mataPelajaran?->deskripsi_cp ?? '');
  if (!rawCp) {
    alert('Mata pelajaran ini belum memiliki data Capaian Pembelajaran (CP).');
    return;
  }

  // Ambil intisari CP
  let cleanCp = rawCp.replace(/^peserta didik mampu\s+/i, '').trim();
  let snippetCp = cleanCp.length > 90 ? cleanCp.substring(0, 85) + '...' : cleanCp;

  const rows = document.querySelectorAll('tbody tr');
  let filledCount = 0;

  rows.forEach(row => {
    const inputs = row.querySelectorAll('input[type="number"]');
    let total = 0, count = 0;
    inputs.forEach(inp => {
      const val = parseFloat(inp.value);
      if (!isNaN(val) && val > 0) {
        total += val;
        count++;
      }
    });

    const avg = count > 0 ? (total / count) : 0;
    const descInput = row.querySelector('input[name^="deskripsi["]');
    if (!descInput) return;

    if (avg >= 85) {
      descInput.value = `Menunjukkan penguasaan yang sangat istimewa dalam ${snippetCp}`;
    } else if (avg >= 75) {
      descInput.value = `Menunjukkan penguasaan yang sangat baik dalam ${snippetCp}`;
    } else if (avg >= 65) {
      descInput.value = `Menunjukkan pemahaman yang cukup baik dalam ${snippetCp}, perlu latihan berkelanjutan`;
    } else if (avg > 0) {
      descInput.value = `Perlu pendampingan dan bimbingan lebih lanjut dalam memahami ${snippetCp}`;
    } else {
      descInput.value = `Perlu bimbingan dalam ${snippetCp}`;
    }
    filledCount++;
  });

  if (filledCount > 0) {
    alert(`✔ Berhasil meng-generate ${filledCount} deskripsi capaian siswa berdasarkan nilai & CP resmi! Silakan periksa kembali sebelum menyimpan.`);
  }
}
</script>
@endpush
@endsection
